export const ZODIAC_SIGNS = [
    { name: 'Aries', sanskritName: 'Mesh', symbol: '♈', element: 'Fire', ruling: 'Mars', dateRange: 'Mar 21 – Apr 19', quality: 'Cardinal' },
    { name: 'Taurus', sanskritName: 'Vrish', symbol: '♉', element: 'Earth', ruling: 'Venus', dateRange: 'Apr 20 – May 20', quality: 'Fixed' },
    { name: 'Gemini', sanskritName: 'Mithun', symbol: '♊', element: 'Air', ruling: 'Mercury', dateRange: 'May 21 – Jun 20', quality: 'Mutable' },
    { name: 'Cancer', sanskritName: 'Kark', symbol: '♋', element: 'Water', ruling: 'Moon', dateRange: 'Jun 21 – Jul 22', quality: 'Cardinal' },
    { name: 'Leo', sanskritName: 'Simha', symbol: '♌', element: 'Fire', ruling: 'Sun', dateRange: 'Jul 23 – Aug 22', quality: 'Fixed' },
    { name: 'Virgo', sanskritName: 'Kanya', symbol: '♍', element: 'Earth', ruling: 'Mercury', dateRange: 'Aug 23 – Sep 22', quality: 'Mutable' },
    { name: 'Libra', sanskritName: 'Tula', symbol: '♎', element: 'Air', ruling: 'Venus', dateRange: 'Sep 23 – Oct 22', quality: 'Cardinal' },
    { name: 'Scorpio', sanskritName: 'Vrischika', symbol: '♏', element: 'Water', ruling: 'Mars', dateRange: 'Oct 23 – Nov 21', quality: 'Fixed' },
    { name: 'Sagittarius', sanskritName: 'Dhanu', symbol: '♐', element: 'Fire', ruling: 'Jupiter', dateRange: 'Nov 22 – Dec 21', quality: 'Mutable' },
    { name: 'Capricorn', sanskritName: 'Makar', symbol: '♑', element: 'Earth', ruling: 'Saturn', dateRange: 'Dec 22 – Jan 19', quality: 'Cardinal' },
    { name: 'Aquarius', sanskritName: 'Kumbh', symbol: '♒', element: 'Air', ruling: 'Saturn', dateRange: 'Jan 20 – Feb 18', quality: 'Fixed' },
    { name: 'Pisces', sanskritName: 'Meen', symbol: '♓', element: 'Water', ruling: 'Jupiter', dateRange: 'Feb 19 – Mar 20', quality: 'Mutable' },
];

export const ELEMENT_COLORS: Record<string, string> = {
    Fire: '#ef4444', Earth: '#84cc16', Air: '#3b82f6', Water: '#06b6d4'
};

export const COMPAT_MATRIX: number[][] = [
    [78, 42, 83, 47, 93, 53, 68, 50, 95, 40, 82, 57],
    [42, 80, 48, 90, 55, 92, 65, 85, 38, 95, 45, 82],
    [83, 48, 76, 50, 85, 58, 92, 42, 80, 45, 93, 52],
    [47, 90, 50, 78, 48, 82, 52, 92, 45, 80, 42, 95],
    [93, 55, 85, 48, 82, 50, 75, 55, 92, 42, 78, 45],
    [53, 92, 58, 82, 50, 78, 52, 75, 48, 90, 55, 65],
    [68, 65, 92, 52, 75, 52, 72, 60, 78, 55, 90, 48],
    [50, 85, 42, 92, 55, 75, 60, 80, 48, 82, 50, 88],
    [95, 38, 80, 45, 92, 48, 78, 48, 82, 45, 85, 50],
    [40, 95, 45, 80, 42, 90, 55, 82, 45, 78, 50, 75],
    [82, 45, 93, 42, 78, 55, 90, 50, 85, 50, 76, 52],
    [57, 82, 52, 95, 45, 65, 48, 88, 50, 75, 52, 80],
];

export const PAIR_INSIGHTS: Record<string, { insight: string; chemistry: string; daily: string }> = {
    '0-6': { insight: 'The Ram and the Scales \u2014 one of astrology\'s most electrifying opposite-sign pairings. Aries charges forward with bold instinct while Libra deliberates with elegant grace. This polarity creates a magnetic push-pull that keeps both constantly alive and engaged.', chemistry: 'Off the charts. Aries\' raw passion ignites Libra\'s romantic nature, and Libra\'s charm softens Aries\' rough edges. This is the couple who turn heads wherever they go \u2014 individually stunning, together magnetic.', daily: 'Expect lively debates and passionate reconciliations. Aries decides in a flash; Libra considers every angle. Learning to blend urgency with thoughtful pace creates a beautifully balanced dynamic.' },
    '1-7': { insight: 'Two of the most intensely loyal and stubborn signs facing each other. Taurus seeks earthly comfort and security; Scorpio seeks emotional depth and transformation. This combination creates an unshakeable bond \u2014 or an immovable standstill.', chemistry: 'Intensely physical and deeply emotional. Taurus grounds Scorpio\'s intensity while Scorpio draws Taurus into emotional depths they rarely explore. The magnetism is almost gravitational.', daily: 'Both are deeply private and slow to trust, which paradoxically creates a profound safe space. Daily life is structured, sensual, and intensely private \u2014 a world built for two.' },
    '2-8': { insight: 'The Twins and the Archer \u2014 two freedom-loving, intellectually insatiable signs who recognize each other immediately. Both despise boredom and love adventure, making this a naturally exciting pairing built on friendship and mutual admiration.', chemistry: 'Light, playful, and electric. These two flirt with ideas as much as with each other. The intellectual spark creates a relationship that never grows stale.', daily: 'Life together is one long adventure. Both are adaptable, so routines rarely take hold. The challenge is building enough stability to make the relationship last beyond the excitement.' },
    '3-9': { insight: 'The Crab and the Sea-Goat \u2014 the most complementary opposite pair. Cancer provides emotional warmth and nurturing that Capricorn secretly craves; Capricorn provides stability and ambition that Cancer needs to feel safe. Together they build both a home and an empire.', chemistry: 'Deep and growing. This isn\'t explosive chemistry \u2014 it deepens steadily over years. Cancer melts Capricorn\'s stoic exterior while Capricorn gives Cancer a structure to pour their love into.', daily: 'One of astrology\'s most functional partnerships. Cancer manages the emotional home while Capricorn handles worldly affairs. They complement each other so naturally that day-to-day life flows with remarkable ease.' },
    '4-10': { insight: 'The Lion and the Water Bearer \u2014 a partnership between the individual and the collective. Leo shines with personal magnetism; Aquarius shines with visionary ideas. Both are fixed signs who are fiercely stubborn \u2014 and fiercely loyal.', chemistry: 'Fascinating and unpredictable. Leo finds Aquarius\' originality endlessly intriguing; Aquarius is magnetized by Leo\'s warm radiance. They challenge each other in ways no other sign can.', daily: 'Power struggles are common since both are natural leaders. Aquarius needs intellectual freedom; Leo needs personal recognition. Celebrating each other\'s unique genius without competing is the key.' },
    '5-11': { insight: 'The Virgin and the Fish \u2014 the healer and the dreamer. Virgo brings precision, practicality, and service; Pisces brings imagination, compassion, and intuition. Each has exactly what the other lacks, creating a beautifully healing union.', chemistry: 'Tender and deeply nurturing. Virgo\'s attentiveness makes Pisces feel truly cared for; Pisces\' unconditional acceptance melts Virgo\'s self-criticism. Together they create a sanctuary.', daily: 'Virgo brings structure to Pisces\' dreamy world; Pisces softens Virgo\'s tendency toward criticism. Daily life is gentle, caring, and surprisingly productive when they combine their strengths.' },
    '0-4': { insight: 'Two fire signs that instantly recognize each other as equals. Aries brings pioneering energy and spontaneity; Leo brings royal confidence and warmth. Together they are a force of nature \u2014 passionate, ambitious, and irresistibly magnetic.', chemistry: 'Explosive and addictive. Both are passionate, dramatic, and romantic in big gestures. This is the couple who could fill an entire love story with just their first month together.', daily: 'Both need to lead, which creates regular power struggles. But the same fire that causes clashes also creates passionate reconciliations. Life together is never quiet \u2014 and neither would have it any other way.' },
    '0-8': { insight: 'The Ram and the Archer \u2014 two freedom-loving fire signs who inspire the world-changing best in each other. Aries has the initiative; Sagittarius has the philosophy. Together they can move mountains while laughing the entire way.', chemistry: 'Effortlessly fun and naturally hot. These two fall into spontaneous adventures and build on each other\'s enthusiasm in a way that makes ordinary moments feel extraordinary.', daily: 'Independence is essential for both. They thrive as partners who give each other space to grow individually, coming together to share adventures. Commitment comes naturally when it doesn\'t feel like a cage.' },
    '4-8': { insight: 'Two of the most vibrant signs together create a partnership that radiates joy, generosity, and adventure. Both are natural entertainers with a deep love of life. Their shared optimism makes them a couple others genuinely enjoy being around.', chemistry: 'Warm, playful, and deeply romantic. Leo\'s theatrical passion is beautifully matched by Sagittarius\' adventurous spirit. Together they create memories that feel like a highlight reel.', daily: 'Both can be inconsistent with mundane realities. They need to consciously build practical foundations. But the laughter, joy, and warmth they share makes the effort entirely worthwhile.' },
    '1-5': { insight: 'Two earth signs whose values align with remarkable precision \u2014 both prize loyalty, quality, reliability, and building something lasting. Taurus brings sensual devotion; Virgo brings brilliant discernment. Together they build a love that improves every passing year.', chemistry: 'Slow-burning and deeply satisfying. No fireworks \u2014 instead, a growing warmth that becomes one of the most physically and emotionally comfortable partnerships in the zodiac.', daily: 'Exceptionally functional. Taurus handles sensory comforts; Virgo handles details and organization. Their home is immaculate, beautifully appointed, and filled with quiet contentment.' },
    '1-9': { insight: 'Two earth signs who understand ambition, loyalty, and the satisfaction of building something that lasts. Taurus wants security and comfort; Capricorn wants achievement and legacy. Together they build both \u2014 and neither has to compromise their core values.', chemistry: 'Understated but deeply powerful. The attraction is based on mutual respect and admiration for each other\'s qualities. It grows steadily stronger over time.', daily: 'One of astrology\'s most naturally compatible daily dynamics. Both are reliable, hardworking, and practical. They build shared routines and goals that make life feel stable, meaningful, and progressively more rewarding.' },
    '5-9': { insight: 'Two of the most competent, disciplined, and discerning signs together. Both are highly analytical, deeply responsible, and committed to excellence. They understand each other\'s standards and meet them without being asked.', chemistry: 'Intellectual and quietly passionate. These two fall in love over shared values, deep conversations, and watching each other handle life with exceptional competence.', daily: 'Extraordinarily effective. Together they are a high-functioning team who supports each other\'s ambitions while maintaining a meticulously organized and comfortable home life.' },
    '2-6': { insight: 'Two air signs in perfect intellectual harmony. Gemini brings wit, curiosity, and mental agility; Libra brings charm, grace, and elegant balance. Together they create a relationship that is endlessly stimulating, socially dazzling, and intellectually alive.', chemistry: 'Light, charming, and mentally electric. They fall in love through conversation and stay in love through constant mental stimulation. Their social life is often the envy of every couple they know.', daily: 'Beautiful in theory, occasionally challenging in practice \u2014 both can avoid difficult emotional conversations. Building the habit of going deeper makes an already wonderful partnership truly unshakeable.' },
    '2-10': { insight: 'Two visionary air signs who push each other\'s thinking to new heights. Gemini collects ideas; Aquarius synthesizes them into world-changing visions. Together they are the most intellectually innovative pair in the zodiac.', chemistry: 'Uniquely electric. Both find each other endlessly fascinating, which is rare. The mental chemistry appears immediately and only deepens as they discover each other\'s unconventional depths.', daily: 'Conversation is constant, ideas are everywhere, and life together feels like one continuous discovery. The challenge is ensuring emotional needs don\'t get lost in the intellectual whirlwind.' },
    '6-10': { insight: 'Two idealistic air signs who share a vision for a more beautiful, just world. Libra pursues harmony and fairness in personal relationships; Aquarius pursues justice and innovation for humanity. Together their love feels like a shared mission.', chemistry: 'Intellectually magnetic and socially brilliant. These two understand each other with unusual ease, finding a kindred spirit who matches their eloquence and depth of thought.', daily: 'Effortlessly harmonious. Both are socially gifted, thoughtful, and fair-minded. They navigate disagreements with unusual grace and build a partnership as much a friendship as a romance.' },
    '3-7': { insight: 'Two intensely emotional water signs who create a bond of extraordinary depth and loyalty. Cancer nurtures from unconditional love; Scorpio loves with all-consuming intensity. Together they create a sanctuary of total emotional trust.', chemistry: 'Profound and magnetic. Both are highly intuitive and read each other without words. The emotional depth they reach together is rarely touched by any other combination.', daily: 'Deeply private, beautifully intimate, and intensely loyal. Home is their sanctuary and their relationship their most sacred space. Both need to watch for emotional intensity tipping into possessiveness.' },
    '3-11': { insight: 'Two of the most compassionate, intuitive, and romantically gifted signs in the zodiac. Cancer creates a home filled with love and security; Pisces fills it with magic, imagination, and transcendent tenderness. One of astrology\'s most naturally romantic combinations.', chemistry: 'Ethereal and deeply moving. Both are highly sensitive and respond to each other\'s emotional states with extraordinary empathy. The love between them can feel genuinely otherworldly.', daily: 'Beautifully gentle but requires both to build practical foundations together. Left to their own devices, they drift into beautiful dreams that need grounding in real-world structure.' },
    '7-11': { insight: 'Two deeply spiritual water signs who recognize each other at a soul level. Scorpio dives deep to find hidden truths; Pisces dissolves boundaries in search of universal love. Together they reach emotional and spiritual depths that few couples ever access.', chemistry: 'Intensely powerful and almost mystical. This is the combination of profound soul recognition \u2014 both feel understood in ways they never have with anyone else.', daily: 'Both need emotional intensity and spiritual connection, which they naturally provide for each other. The challenge is maintaining healthy boundaries so the relationship remains nourishing rather than enmeshing.' },
    '0-2': { insight: 'Aries\' bold action meets Gemini\'s brilliant mind. Ideas become reality at lightning speed \u2014 Gemini provides the concept, Aries provides the courage to execute. Their energy together is infectious and unstoppable.', chemistry: 'Playful, exciting, and mentally stimulating. Both love novelty and bring out each other\'s most adventurous side. The spark is both intellectual and spontaneous.', daily: 'Dynamic and rarely boring. Both are fast-moving and adaptable. The challenge is slowing down enough to deepen the emotional connection beneath the exciting surface.' },
    '1-3': { insight: 'Two of the most naturally domestic and nurturing signs in the zodiac. Taurus builds security; Cancer creates emotional warmth. Together they create astrology\'s most beautiful home \u2014 physically comfortable, emotionally safe, and deeply loving.', chemistry: 'Tender, warm, and deeply sensual. Both love physical comfort and emotional intimacy, creating a naturally affectionate bond that feels like coming home.', daily: 'Beautifully harmonious. Both prioritize home, family, and security, making shared life a model of warmth and stability. This partnership often lasts a lifetime.' },
    '4-6': { insight: 'The Lion and the Scales \u2014 a glamorous, socially brilliant pairing. Both love beauty, luxury, and being adored. Leo provides the dramatic flair; Libra provides the elegant taste. Together they are the most stylish couple in any room.', chemistry: 'Warm, romantic, and visually stunning. Both are natural performers and aesthetes who enhance each other\'s allure. Their mutual admiration creates a deeply affirming bond.', daily: 'Usually harmonious, as both prioritize beauty, harmony, and social grace. Minor friction arises when Leo\'s ego needs more spotlight than Libra wants to give \u2014 but Libra\'s charm usually resolves it effortlessly.' },
    '5-7': { insight: 'Two of the most perceptive and analytical signs in the zodiac who see through pretense immediately. Virgo\'s discernment meets Scorpio\'s depth \u2014 together they communicate with unusual honesty and build trust through genuine understanding.', chemistry: 'Slow-building but surprisingly intense. Both take time to trust, which makes their eventual intimacy feel hard-earned and profoundly real.', daily: 'Highly effective together. Virgo\'s precision combines with Scorpio\'s strategic depth to make them a formidably capable couple. Their home is run with quiet excellence.' },
    '6-8': { insight: 'Libra\'s romantic elegance and Sagittarius\' philosophical adventure create a beautiful meeting of heart and mind. Both love beauty, truth, and the finer experiences of life. Their conversations flow effortlessly and their social life is richly fulfilling.', chemistry: 'Light, warm, and romantically generous. Both are naturally affectionate and bring out each other\'s optimism. Dating feels like a beautifully curated adventure.', daily: 'Enjoyable and varied. Both love socializing and experiencing new things. The challenge is building enough depth beneath the beautiful surface to weather difficult seasons.' },
    '7-9': { insight: 'Two of the most ambitious, disciplined, and quietly powerful signs. Scorpio brings emotional depth and strategic brilliance; Capricorn brings structure, resilience, and worldly achievement. Together they are a formidable force \u2014 privately devoted, publicly impressive.', chemistry: 'Intense and deeply respectful. Both recognize and respect the other\'s power without feeling threatened. This mutual respect is the foundation of their magnetic attraction.', daily: 'Serious, purposeful, and surprisingly intimate behind closed doors. Both work hard and appreciate a partner who matches their ambition and understands the demands of high achievement.' },
    '8-10': { insight: 'Two visionary free spirits who share a deep love of truth, freedom, and humanity. Sagittarius explores wisdom through experience; Aquarius through revolutionary ideas. Together they are among the most forward-thinking, inspiring couples in the zodiac.', chemistry: 'Electrifying and unique. Both are unconventional and find in each other a rare person who truly understands their need for freedom and love of ideas.', daily: 'Genuinely fun, endlessly interesting, and joyfully unpredictable. Building shared commitments requires conscious effort but the friendship at their foundation makes the relationship naturally resilient.' },
    '9-11': { insight: 'Structure meets soul \u2014 Capricorn\'s worldly ambition is beautifully softened by Pisces\' spiritual depth. Capricorn gives Pisces the foundation to make their dreams real; Pisces gives Capricorn a reason to pursue more than just achievement.', chemistry: 'Surprisingly tender. Capricorn\'s stoic exterior melts in Pisces\' compassionate presence. Pisces feels genuinely safe in Capricorn\'s capable arms. The quiet devotion grows beautifully.', daily: 'Complementary in the best way. Capricorn handles the practical world; Pisces handles the emotional and spiritual dimensions. Together they cover every aspect of a full and meaningful life.' },
};

// ─── NAME COMPATIBILITY — CHALDEAN NUMEROLOGY ────────────────────────────────
export const CHALDEAN_MAP: Record<string, number> = {
    a: 1, b: 2, c: 3, d: 4, e: 5, f: 8, g: 3, h: 5, i: 1, j: 1, k: 2, l: 3, m: 4, n: 5, o: 7, p: 8, q: 1, r: 2, s: 3, t: 4, u: 6, v: 6, w: 6, x: 5, y: 1, z: 7
};

export const NAME_RASHI_MAP: Record<string, number> = {
    'a': 0, 'l': 0, 'e': 0, // Aries
    'b': 1, 'v': 1, 'u': 1, 'w': 1, // Taurus
    'k': 2, 'g': 2, 'q': 2, // Gemini
    'h': 3, 'd': 3, // Cancer
    'm': 4, // Leo
    'p': 5, 't': 5, // Virgo
    'r': 6, // Libra
    'n': 7, 'y': 7, // Scorpio
    'f': 8, 'o': 8, // Sagittarius
    'j': 9, // Capricorn
    's': 10, 'x': 10, // Aquarius
    'c': 11, 'z': 11 // Pisces
};

export const NUM_ARCHETYPES: Record<number, { title: string; planet: string; traits: string[]; description: string; inLove: string }> = {
    1: { title: 'The Pioneer', planet: 'Sun', traits: ['Natural leader', 'Independent', 'Ambitious', 'Courageous'], description: 'Those with name number 1 carry the energy of the Sun — bold, pioneering, and magnetic. They forge their own path and radiate powerful self-confidence that draws others naturally.', inLove: 'In love, they are passionate and devoted but need a partner who gives them space to lead. They show love through bold gestures and unwavering loyalty.' },
    2: { title: 'The Peacemaker', planet: 'Moon', traits: ['Deeply empathetic', 'Diplomatic', 'Intuitive', 'Nurturing'], description: 'Name number 2 carries the gentle power of the Moon — deeply sensitive, intuitive, and gifted at creating harmony. They read emotions like poetry and build bridges between hearts.', inLove: 'In love, they are the most devoted and emotionally present partners. They feel everything deeply and need reciprocal tenderness and emotional safety to truly flourish.' },
    3: { title: 'The Creator', planet: 'Jupiter', traits: ['Expressive', 'Joyful', 'Creative', 'Charismatic'], description: 'Name number 3 vibrates with Jupiter\'s expansive joy — overflowing with creativity, wit, and infectious optimism. They light up any room and inspire those around them with visionary ideas.', inLove: 'In love, they are playful, romantic, and deeply expressive. They need a partner who appreciates their creative soul and keeps the relationship fresh and alive.' },
    4: { title: 'The Builder', planet: 'Rahu', traits: ['Disciplined', 'Reliable', 'Methodical', 'Grounded'], description: 'Name number 4 carries Rahu\'s energy of transformation through discipline. They are the steady foundation others lean on — hardworking, trustworthy, and deeply principled.', inLove: 'In love, they are loyal beyond measure and deeply protective. They may not be the most vocal, but their commitment speaks louder than words ever could.' },
    5: { title: 'The Adventurer', planet: 'Mercury', traits: ['Versatile', 'Quick-minded', 'Free-spirited', 'Magnetic'], description: 'Name number 5 pulses with Mercury\'s quicksilver energy — restless, curious, and endlessly adaptable. They crave variety, thrive on stimulation, and bring electric energy to everything.', inLove: 'In love, they are exciting and unpredictable partners who keep the relationship alive with spontaneity. They need freedom and mental stimulation to stay deeply connected.' },
    6: { title: 'The Nurturer', planet: 'Venus', traits: ['Loving', 'Responsible', 'Harmonious', 'Devoted'], description: 'Name number 6 resonates with Venus — the most loving vibration in Chaldean numerology. They are natural caretakers who create beauty, warmth, and comfort everywhere they go.', inLove: 'In love, they are extraordinarily devoted, romantic, and giving. They pour their heart into relationships and thrive when their love and effort are genuinely appreciated.' },
    7: { title: 'The Mystic', planet: 'Ketu', traits: ['Spiritual', 'Introspective', 'Wise', 'Perceptive'], description: 'Name number 7 carries Ketu\'s mystical depth — deeply spiritual, highly intuitive, and philosophical. They are the seekers of hidden truths and possess wisdom beyond their years.', inLove: 'In love, they are selective and deeply loyal once committed. They need an intellectually and spiritually stimulating partner who respects their need for solitude and depth.' },
    8: { title: 'The Achiever', planet: 'Saturn', traits: ['Powerful', 'Strategic', 'Ambitious', 'Resilient'], description: 'Name number 8 pulses with Saturn\'s karmic power — destined for authority, material mastery, and transformational impact. They overcome tremendous challenges to achieve lasting success.', inLove: 'In love, they are intensely devoted but may struggle to express emotions openly. They show love through actions — providing, protecting, and building a stable future together.' },
    9: { title: 'The Sage', planet: 'Mars', traits: ['Compassionate', 'Universal', 'Idealistic', 'Magnetic'], description: 'Name number 9 vibrates with Mars\' universal compassion — old souls who carry the wisdom of lifetimes. They are humanitarian, deeply empathetic, and magnetically attractive to others.', inLove: 'In love, they are deeply romantic and selfless. They seek a soulmate-level connection and can be intensely passionate when they find a partner who matches their emotional depth.' },
    11: { title: 'The Illuminator', planet: 'Moon/Sun', traits: ['Highly intuitive', 'Visionary', 'Inspirational', 'Sensitive'], description: 'Master Number 11 is the most intuitive in Chaldean numerology — a bridge between the physical and spiritual realms. They carry an extraordinary gift of insight and inspiration.', inLove: 'In love, they are deeply spiritual partners who seek a transcendent connection. They need someone who understands their heightened sensitivity and visionary nature.' },
    22: { title: 'The Master Builder', planet: 'Uranus', traits: ['Visionary', 'Powerful', 'Practical', 'Legendary'], description: 'Master Number 22 is the most powerful in Chaldean numerology — combining vision with the practical ability to manifest great things. They are destined to leave a lasting legacy.', inLove: 'In love, they are steadfast, ambitious, and deeply committed. They seek a partner who shares their grand vision for life and supports their world-changing ambitions.' },
};

export const NUM_COMPAT: Record<string, number> = {
    '1-1': 75, '1-2': 78, '1-3': 90, '1-4': 62, '1-5': 88, '1-6': 82, '1-7': 68, '1-8': 64, '1-9': 92,
    '2-2': 82, '2-3': 75, '2-4': 78, '2-5': 65, '2-6': 96, '2-7': 85, '2-8': 65, '2-9': 78,
    '3-3': 85, '3-4': 60, '3-5': 94, '3-6': 92, '3-7': 65, '3-8': 62, '3-9': 98,
    '4-4': 75, '4-5': 60, '4-6': 88, '4-7': 75, '4-8': 92, '4-9': 75,
    '5-5': 82, '5-6': 65, '5-7': 88, '5-8': 68, '5-9': 92,
    '6-6': 92, '6-7': 62, '6-8': 68, '6-9': 95,
    '7-7': 78, '7-8': 60, '7-9': 75,
    '8-8': 78, '8-9': 65,
    '9-9': 90,
};

export const NUM_INSIGHTS: Record<string, string> = {
    '1-1': `Two Pioneers together — a union of two powerful, independent souls. Channel combined ambition into shared goals rather than competing.`,
    '1-2': `The King and Queen — a naturally balanced union. Person 1's radiant solar energy and Person 2's gentle lunar reflection create a legacy of both power and grace.`,
    '1-3': `Pioneering Sun energy and Jupiterian creativity form a naturally magnetic pair. Together you can achieve and create beautiful things.`,
    '1-4': `Leadership meets structure — Sun and Rahu energy create an unconventional powerhouse. Together you challenge the status quo to build something unique.`,
    '1-5': `Brilliance and speed — pioneering spirit matches quick intellectual wit. A pair that communicates with electric energy and constant discovery.`,
    '1-6': `Glory meets Love — Sun energy find a beautiful home in Venusian nurturing. A high-resonance bond full of romance, loyalty, and social grace.`,
    '1-7': `The Leader and the Mystic — a journey of inner discovery. One provides the outer direction while the other provides the spiritual depth to your shared path.`,
    '1-8': `Sun meets Saturn — a powerful karmic legacy. Radiant will and disciplined mastery must balance power to achieve enduring, world-changing success.`,
    '1-9': `The Pioneer meets the Sage — a deeply karmic connection. One brings bold direction while the other brings universal wisdom, creating a beautifully complete partnership.`,
    '2-2': `Two Peacemakers together — a world of deep emotional understanding and wordless intuition. You nurture each other's souls with absolute tenderness.`,
    '2-3': `Intuition meets Wisdom — Moon energy blends beautifully with Jupiterian vision. A partnership full of compassion, social harmony, and shared joy.`,
    '2-4': `Emotional Intensity — sensitivity and Rahu architecture create a bond that must navigate deep emotional transformations to find its stable heart.`,
    '2-5': `Emotion meets Intellect — sensitivity and quick wit create a playful, communicative, and intellectually stimulating bond.`,
    '2-6': `The Peacemaker and the Nurturer — one of the most naturally harmonious combinations. Both carry Venus-Moon energy that blends with effortless warmth.`,
    '2-7': `Mystical Resonance — psychic intuition and spiritual depth create a rare bond that transcends words. You share secrets of the soul.`,
    '2-8': `Sensitivity meets Strength — emotional depth and Saturnian resilience create a balanced bond built on maturity and unwavering support.`,
    '2-9': `Softness meets Courage — Moon energy harmonises with Martian passion. A deeply devoted and emotionally charged pairing full of vitality.`,
    '3-3': `Two Visionaries — a life full of expansive joy, creative growth, and shared optimism. Together you inspire everyone around you with your combined light.`,
    '3-4': `Visionary Building — expansive growth and structured discipline create a partnership that can materialize even the grandest creative dreams.`,
    '3-5': `The Creator and the Messenger — a brilliant combination of vision and speed. Together you communicate ideas with infectious enthusiasm and success.`,
    '3-6': `Jupiter creativity beautifully harmonises with Venus nurturing. A warm, expressive, and deeply loving combination full of joy and devotion.`,
    '3-7': `Wisdom meets Mystery — a profound philosophical bond. One brings the light of understanding while the other provides the depth of spiritual insight.`,
    '3-8': `Vision meets Endurance — expansive ideas find a steady vessel in Saturnian discipline. A powerhouse pair that builds a lasting legacy.`,
    '3-9': `The Creator and the Sage — a divinely inspired combination. Joyful creativity meets deep compassion, creating a relationship full of meaning and beauty.`,
    '4-4': `Two Architects — a technical and unconventional union that builds according to its own unique rules. Together you redefine what is possible through discipline.`,
    '4-5': `Structure meets Agility — disciplined approach and quick Mercury mind create a technically brilliant and highly adaptable partnership.`,
    '4-6': `Building Harmony — reliable energy provides the foundation for Venusian beauty. A loyal partnership that values a stable and aesthetic home.`,
    '4-7': `The Builder and the Mystic — a karmic axis of transformation. Together you bridge the physical and spiritual worlds with unique and powerful insight.`,
    '4-8': `Two Saturn-influenced names — a powerhouse built on discipline, loyalty, and shared ambition. Together you build something truly lasting and meaningful.`,
    '4-9': `Discipline meets Valor — Mars and Rahu energies create a pioneering force. You have the discipline to execute even your most courageous shared visions.`,
    '5-5': `Double Quicksilver — a relationship moving at the speed of thought. Constant communication, travel, and intellectual discovery keep your bond electric.`,
    '5-6': `Wit meets Beauty — Mercury energy find a charming partner in Venusian grace. A socially dazzling and artistic pairing that thrives on joy.`,
    '5-7': `Analysis meets Intuition — logical mind matches spiritual perspective. Together you solve the mysteries of life with both wit and wisdom.`,
    '5-8': `Strategy and Speed — quick mind and strategic patience create a partnership built for material and social success through clever effort.`,
    '5-9': `The Adventurer and the Sage — constant motion and universal growth. One brings the curiosity and the other brings the courage to explore all of life together.`,
    '6-6': `Pure Venusian Harmony — a home full of absolute beauty, devotion, and romance. You create a sanctuary of love that others find deeply inspiring.`,
    '6-7': `Love meets Spirit — Venusian heart and Ketu depth create a gentle, spiritualized love that values inner connection over outer show.`,
    '6-8': `Devotion meets Reliability — nurturing heart finds security in disciplined power. A stable, loyal, and deeply committed lifelong partnership.`,
    '6-9': `Venus meets Mars in this deeply loving and passionate combination. Devotion harmonises beautifully with universal compassion.`,
    '7-7': `Two Mystics together — a rare and profoundly spiritual connection. You share an intuitive understanding of each other that goes beyond words.`,
    '7-8': `Depth meets Duty — a serious, philosophical bond. Together you explore the deeper responsibilities of life with maturity and spiritual resilience.`,
    '7-9': `Wisdom meets Spirit — a high-vibrational soul connection. Together you explore the deeper meaning of life with mutual respect and profound intuition.`,
    '8-8': `Double Powerhouse — a karmic bond of immense responsibility and ambition. You are destined to achieve grand things through combined resilience and duty.`,
    '8-9': `Strength meets Courage — Mars and Saturn combined create an unstoppable force. You overcome any obstacle together through discipline and fire.`,
    '9-9': `Two Sages together — a union of two old souls. You share a deeply humanitarian outlook and an intensely passionate, selfless way of loving.`,
    '11-11': `Double Illuminators — a rare, high-frequency spiritual union. Your combined intuition and visionary light can inspire entire communities.`,
    '11-22': `The Illuminator and the Master Builder — the ultimate combination of spiritual vision and material mastery. Together you manifest profound global change.`,
    '22-22': `Double Master Builders — an exceptionally powerful legacy-building union. You carry the vibration of someone destined to change the architectural or social world.`,
};

